### PR TITLE
Codefresh Unified Error Modeling (draft 1)

### PR DESCRIPTION
**Pull request by liorshalev01**

### CODE REVIEW

**Comment by liorshalev01** [comment]
# Codefresh Unified Error Modeling (draft 1)
## CFError
- CFError should be the base class for all error types.
- CFError itself should inherit from VError.
- Each module should define it’s possible thrown errors by inheriting from CFError, optionally adding additional relevant members, for each error type.

# Usage Example:
```javascript
// some http api module defines its thrown error types.
// error types should be inherited from CFError.
class CFHttpError extends CFError {
    constructor(options, errorCode) {
        super(options);

        // define http error code
        this.errorCode = errorCode;
    }
}

// define the Http Unauthorize (401) error
class CFHttpUnauthorizedError extends CFHttpError {
    constructor(options) {
        super(options, 401);
    }
}

// define the Http Forbidden (403) error
class CFHttpErrorForbidden extends CFHttpError {
    constructor(options) {
        super(options, 403);
    }
}

...
```

## Logger
- Logger should define severity level (`verbose, debug, info, warning, and error`).
- Logger should define logger categories. For example, `Github`, `Builder`, etc.
- Logger should support appender types. For example, `Console`, `File`, etc.
_ Logger should should support appender and filters configurations.
# Usage Example:
```
// logger.json
{
  "appenders": [
    {
      "type": "categoryFilter",
      "exclude": [
        "Builder"
      ],
      "appender": {
        "type": "console"
      }
    }
  ]
}

...

// builder-task.js
const logger = require("logger").getLogger("Builder");
logger.info("Build started. task %s", taskID);
...
logger.warning(...);

```

**Comment by liorshalev01** [comment]
# Codefresh Unified Error Modeling (draft 1)
## CFError
- CFError should be the base class for all error types.
- CFError itself should inherit from VError.
- Each module should define it’s possible thrown errors by inheriting from CFError, optionally adding additional relevant members, for each error type.

# Usage Example:
```javascript
// some http api module defines its thrown error types.
// error types should be inherited from CFError.
class CFHttpError extends CFError {
    constructor(options, errorCode) {
        super(options);

        // define http error code
        this.errorCode = errorCode;
    }
}

// define the Http Unauthorize (401) error
class CFHttpUnauthorizedError extends CFHttpError {
    constructor(options) {
        super(options, 401);
    }
}

// define the Http Forbidden (403) error
class CFHttpErrorForbidden extends CFHttpError {
    constructor(options) {
        super(options, 403);
    }
}

...
```

## Logger
- Logger should define severity level (`verbose, debug, info, warning, and error`).
- Logger should define logger categories. For example, `Github`, `Builder`, etc.
- Logger should support appender types. For example, `Console`, `File`, etc.
_ Logger should should support appender and filters configurations.
# Usage Example:
```
// logger.json
{
  "appenders": [
    {
      "type": "categoryFilter",
      "exclude": [
        "Builder"
      ],
      "appender": {
        "type": "console"
      }
    }
  ]
}

...

// builder-task.js
const logger = require("logger").getLogger("Builder");
logger.info("Build started. task %s", taskID);
...
logger.warning(...);

```

**Comment by liorshalev01** [comment]
# Codefresh Unified Error Modeling (draft 2)

## JavaScript/Node CFError

Inside JavaScript/Node all errors should be reported as an error specific class derived from CFError. CFError itself should inherit from VError.

Each module should define it’s possible thrown errors by inheriting from CFError, optionally adding additional relevant members, for each error type.

### Usage Example:

``` javascript
// Define User Not Found error.
class CFUserNotFoundError extends CFError {
    constructor(options) {
        super(options, 1002)
    }
}

// Define User Already Exists error
class CFUserAlreadyExistsError extends CFError {
    constructor(options, existingUserID) {
        super(options, 1003);
        this.existingUserID = existingUserID;
    }
}
```

# REST Response Errors

Guidelines and best practice taken from

## HTTP Response Code

Success responses should be of the HTTP 2xx response code. Examples:

```
HTTP/1.1 200 OK
HTTP/1.1 201 Created
```

Client requests error responses should be of the HTTP 4xx client error codes. Examples:

```
HTTP/1.1 403 Forbidden
HTTP/1.1 404 Not Found
```

Server error responses should of the HTTP 5xx server error codes. Examples:

```
HTTP/1.1 500 Internal Server Error
```

## HTTP Error Response Body

For 4xx and 5xx response codes, the response body should contains the error description:

```
HTTP/1.1 400 Internal Server Error
{
    "code": <error code>
    "message": <error description>
}
```

It is also possible to return a list of errors, for example:

```
HTTP/1.1 500 Internal Server Error
{
    errors: [
        {
            "code": <error code>
            "message": <error description>
        },
        ...
    ]
}
```

**Comment by bmeiri** [comment]
A few questions:
1. Why should we send back an array of errors? either always send array or never (I prefer never)
2. Where do we add the error code?

**Pull request closed without merging**
